"""migration

Revision ID: 474d2b93458f
Revises:
Create Date: 2022-08-07 20:35:45.077270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "474d2b93458f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("hash", sa.String(length=128), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("system_validated", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_hash"), "posts", ["hash"], unique=False)
    op.create_index(op.f("ix_posts_url"), "posts", ["url"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password_hashed", sa.String(length=128), nullable=False),
        sa.Column("salt", sa.String(length=36), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "detections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=1000), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detections_post_id"), "detections", ["post_id"], unique=False
    )
    op.create_index(
        op.f("ix_detections_user_id"), "detections", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_detections_user_id"), table_name="detections")
    op.drop_index(op.f("ix_detections_post_id"), table_name="detections")
    op.drop_table("detections")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_posts_url"), table_name="posts")
    op.drop_index(op.f("ix_posts_hash"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
